---



- name: Create app root dir
  ansible.builtin.file:
    path: "{{ docker_app_build_root }}/{{ docker_app_name }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Copy app compose file
  ansible.builtin.copy:
    src:  "docker-compose.yml"
    dest: "{{ docker_app_build_root }}/{{ docker_app_name }}/"
    owner: root
    group: root
    mode: 0440 

- name: Copy app env file
  ansible.builtin.copy:
    src:  "env-file"
    dest: "{{ docker_app_build_root }}/{{ docker_app_name }}/.env"
    owner: root
    group: root
    mode: 0440

#- name: Install docker-compose app
#  community.docker.docker_compose:
#    project_src: "{{ docker_app_build_root }}/{{ docker_app_name }}/"
#    state: present

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: "{{ docker_app_name }}"
    compose:
      - "{{ docker_app_build_root }}/{{ docker_app_name }}/docker-compose.yml"
