---

- name: SF ansible tasks - update docker swarm app
  hosts: dmanagers
  remote_user: ruser0
  become: true
  vars:
    docker_service_name: app0_front-end
    docker_service_replicas: 2

  roles:
    - docker_app0_scale
