---
- name: will wait till reachable
  hosts: ansibled
  remote_user: ruser0
  gather_facts: no # important
  roles:
    - wait_for

- name: SF ansible tasks - setup bastion
  hosts: bastion
  remote_user: ruser0
  become: true
  roles:
    - proxy
    - gresolver

- name: SF ansible tasks - bootstrap
  hosts: ansibled
  remote_user: ruser0
  become: true
  roles:
    - proxified_pkg
    - common

- name: SF ansible tasks - deploy docker
  hosts: dmanagers, dworkers
  remote_user: ruser0
  become: true
  roles:
    - docker
    - proxified_docker
#    - test

- name: SF ansible tasks - setup docker swarm managers
  hosts: dmanagers
  remote_user: ruser0
  become: true
  roles:
    - docker_manager

- name: SF ansible tasks - setup docker swarm workers
  hosts: dworkers
  remote_user: ruser0
  become: true
  roles:
    - docker_worker

- name: SF ansible tasks - deploy docker swarm app
  hosts: dmanagers
  remote_user: ruser0
  become: true
  roles:
    - docker_app0
