---

- name: configure proxy acl
  ansible.builtin.lineinfile:
    path: "{{ package_conf_file }}"
    state: present
    regexp: "^Allow {{ var_priv_subnet }}"
    insertafter: "^Allow 127.0.0.1"
    line: "Allow {{ var_priv_subnet }}"
  notify:
    - reload services

- name: configure proxy listen
  ansible.builtin.lineinfile:
    path: "{{ package_conf_file }}"
    state: present
    regexp: "^Listen {{ var_priv_proxy_addr }}"
    insertafter: "^#Listen 192.168.0.1"
    line: "Listen {{ var_priv_proxy_addr }}"
  notify:
    - reload services
